### PR TITLE
Feature/brian release a2

### PR DESCRIPTION
**Pull request by briandoconnor**
Remaining issue is generating a token for Boardwalk:

```
ubuntu@ip-172-31-42-56:~/gitroot/BD2KGenomics/dcc-ops$ redwood/admin/bin/redwood token create -u indexer -s 'aws.upload aws.download'
{"timestamp":1492918587993,"status":500,"error":"Internal Server Error","exception":"org.springframework.jdbc.CannotGetJdbcConnectionException","message":"Could not get JDBC Connection; nested exception is org.postgresql.util.PSQLException: FATAL: password authentication failed for user \"dcc_auth\"","path":"/admin/scopes/indexer"}{"timestamp":1492918588045,"status":401,"error":"Unauthorized","message":"Could not get JDBC Connection; nested exception is org.postgresql.util.PSQLException: FATAL: password authentication failed for user \"dcc_auth\"","path":"/oauth/token"}
```

### CODE REVIEW

**Comment by benjaminran** [comment]
LGTM

**Comment by benjaminran** [comment]
@briandoconnor you saw the password authentication failed error? Carlos had it too but doing `redwood down; redwood up` fixed it. Were your redwood containers recreated from old volumes (i.e. didn't call docker-compose down)?

**Comment by benjaminran** [comment]
(Accidental close)

**Comment by briandoconnor** [comment]
Hi Beni, I saw the auth problem on a totally fresh install.

**Comment by benjaminran** [comment]
If you still have the redwood intance around, could you do `redwood down; redwdood up; redwood token list`?

**Comment by benjaminran** [comment]
That's orthogonal to this PR though. Will close this now - let me know on slack if you try the above for redwood.

**Pull request merged**
